### ISSUE TITLE
Encryption key

### ISSUE THREAD

**Issue by ChirizB13** [lampitosgames/TwitFollowerBot#1]
Hi, this a great work.

And sorry for this question, but this message it shows when I put my Encryption Key:

`AttributeError: 'unicode' object has no attribute 'key'`

I do something wrong?

**Comment by lampitosgames** [comment]
Thanks for your interest in my thing!

I assume you got redirected to twitter to authorize the app, pasted in the code twitter generated, and then the error happened?

I just reproduced the bug.  I'll look into it today.  This script is 2 years old, so we'll see if I can fix it :)

**Comment by lampitosgames** [comment]
Alright.  I think I fixed it.  Looks like tweepy has had some breaking updates since I made this.  It should all be working now.

Just to prevent possible issues, try the following:
- Use python 2.7 (the version this was developed for). I think python 3.x has breaking changes
- The twitter developer landing page has changed.  To get directly to creating apps, go to apps.twitter.com
- The API key is the "consumer key".  The API secret is the "consumer secret".  It should be the third tab over on your twitter app's info screen.
- Also, I just realized it isn't in the readme, but you might need to preface all function calls with TwitFollowerBot.<function>

I'm going to update the readme with some details.  Thanks for pointing out this error! :D
